export interface Env {
  ASSETS: Fetcher;
  DB: D1Database;
  SUB_CACHE: KVNamespace;
  ADMIN_JWT_SECRET: string;
  ADMIN_LOGIN_RATE_LIMIT_WINDOW_SEC: string;
  ADMIN_LOGIN_RATE_LIMIT_MAX_ATTEMPTS: string;
  SUBSCRIPTION_CACHE_TTL: string;
  SUBSCRIPTION_RATE_LIMIT_WINDOW_SEC: string;
  SUBSCRIPTION_RATE_LIMIT_MAX_REQUESTS: string;
  PREVIEW_CACHE_TTL: string;
  SYNC_HTTP_TIMEOUT_MS: string;
  APP_ENV: string;
}
